// Regenerates shared/crossings_data.lua: every level crossing of GTA:SA (the binary IPLs in
// models/gta3.img place traincross1 = 1373 posts and traincross2 = 1374 barrier arms).
//   node tools/gen_crossings.js "C:/Games/GTA San Andreas"
const fs = require('fs');
const path = require('path');
const gta = process.argv[2] || 'C:/Games/GTA San Andreas';
const fd = fs.openSync(path.join(gta, 'models/gta3.img'), 'r');
const hdr = Buffer.alloc(8); fs.readSync(fd, hdr, 0, 8, 0);
const n = hdr.readUInt32LE(4);
const dir = Buffer.alloc(n * 32); fs.readSync(fd, dir, 0, n * 32, 8);
const objs = [];
for (let i = 0; i < n; i++) {
    const name = dir.toString('latin1', i * 32 + 8, i * 32 + 32).replace(/\0.*$/, '');
    if (!/\.ipl$/i.test(name)) continue;
    const off = dir.readUInt32LE(i * 32) * 2048, size = dir.readUInt16LE(i * 32 + 4) * 2048;
    const b = Buffer.alloc(size); fs.readSync(fd, b, 0, size, off);
    if (b.toString('latin1', 0, 4) !== 'bnry') continue;
    const count = b.readUInt32LE(4), instOff = b.readUInt32LE(0x1C);
    for (let k = 0; k < count; k++) {
        const o = instOff + k * 40, id = b.readInt32LE(o + 28);
        if (id !== 1373 && id !== 1374) continue;
        const qz = b.readFloatLE(o + 20), qw = b.readFloatLE(o + 24);
        objs.push({ model: id, x: b.readFloatLE(o), y: b.readFloatLE(o + 4), z: b.readFloatLE(o + 8),
            rz: (-2 * Math.atan2(qz, qw) * 180 / Math.PI + 360) % 360 });
    }
}
// group into crossings (the four objects of one crossing are within ~40 m)
const crossings = [];
for (const o of objs) {
    let c = crossings.find(c => Math.hypot(c.x - o.x, c.y - o.y) < 45);
    if (!c) { c = { x: o.x, y: o.y, objs: [] }; crossings.push(c); }
    c.objs.push(o);
    c.x = c.objs.reduce((s, i) => s + i.x, 0) / c.objs.length;
    c.y = c.objs.reduce((s, i) => s + i.y, 0) / c.objs.length;
}
// the IPL yaw sign is ambiguous: an arm (extending along its +y) must point towards the
// middle of its crossing
for (const c of crossings) for (const o of c.objs) {
    if (o.model !== 1374) continue;
    const toward = (rz) => { const a = rz * Math.PI / 180; const fx = -Math.sin(a), fy = Math.cos(a);
        return fx * (c.x - o.x) + fy * (c.y - o.y); };
    const alt = (360 - o.rz) % 360;
    if (toward(alt) > toward(o.rz)) {
        o.rz = alt;
        const post = c.objs.find(p => p.model === 1373 && Math.hypot(p.x - o.x, p.y - o.y) < 4);
        if (post) post.rz = alt;
    }
}
const f = v => (Math.round(v * 1000) / 1000).toString();
let out = '-- GENERATED by tools/gen_crossings.js from GTA:SA models/gta3.img - do not edit.\n' +
    '-- { x, y = centre, objs = { { model, x, y, z, rz } } }  1373 = post, 1374 = barrier arm\nRW_CROSSING_DATA = {\n';
for (const c of crossings) {
    out += `    { x = ${f(c.x)}, y = ${f(c.y)}, objs = {\n`;
    for (const o of c.objs) out += `        { ${o.model}, ${f(o.x)}, ${f(o.y)}, ${f(o.z)}, ${f(o.rz)} },\n`;
    out += '    } },\n';
}
out += '}\n';
fs.writeFileSync(path.join(__dirname, '..', 'shared', 'crossings_data.lua'), out);
console.log(crossings.length, 'crossings,', objs.length, 'objects');
