// Live smoke test against a running MTA server with the bridge and a probe client:
//   node test/live.smoke.mjs
import { createContext } from '../src/server.js';
import { TOOLS, wrap } from '../src/tools/registry.js';

const ctx = await createContext();
const run = async (name, args = {}) => {
  const def = TOOLS.find((t) => t.name === name);
  const t0 = Date.now();
  const res = await wrap(def, ctx)(args);
  const txt = res.content.find((c) => c.type === 'text')?.text || '';
  const img = res.content.some((c) => c.type === 'image');
  let j; try { j = JSON.parse(txt); } catch { j = txt; }
  const ok = !res.isError;
  console.log(`${ok ? 'OK  ' : 'FAIL'} ${name.padEnd(28)} ${String(Date.now() - t0).padStart(5)}ms ${img ? '[image] ' : ''}${ok ? '' : JSON.stringify(j.error)}`);
  return j;
};
const P = { x: 1849, y: -1460, z: 13 };
await run('get_capability_map');
await run('get_world_map');
await run('inspect_world_map_area', { center: P, size: 600, cellSize: 150 });
const ia = await run('inspect_area', { center: P, radius: 40, detail: 'high' });
console.log('     areaType', ia.geometry?.areaType, 'models', ia.geometry?.worldModelCount, 'bounds measured', ia.geometry?.worldModels?.filter((m) => m.worldBounds).length);
await run('get_area_summary', { center: P });
await run('raycast', { mode: 'down', position: P });
await run('raycast', { mode: 'direction', from: { x: 1849, y: -1460, z: 14 }, heading: 90, length: 60 });
await run('raycast', { mode: 'camera' });
await run('get_ground', { points: [P, [1855, -1450]] });
const spot = await run('find_safe_position', { near: P, for: 'vehicle', model: 416, preferRoad: true, count: 2 });
console.log('     spots', spot.spots?.length, JSON.stringify(spot.rejected));
await run('check_line_of_sight', { from: P, to: { x: 1849, y: -1420, z: 13 } });
await run('list_world_elements', { center: P, radius: 60 });
await run('environment');
await run('get_road_node', { id: 1442188, live: true });
await run('get_connected_road_nodes', { id: 1442188, depth: 2 });
await run('get_road_segment', { from: 1442188, to: 1442192, live: true });
await run('get_nearest_road_segment', { position: P, count: 2 });
const path = await run('find_road_path', { from: 1442188, to: { x: 1180, y: -1330, z: 13 } });
await run('inspect_road_area', { center: P, radius: 80, live: true, maxLiveNodes: 6 });
await run('get_vehicle_models', { category: 'Bike' });
const peds = await run('get_ped_models', { sex: 'female' });
console.log('     female peds', peds.count, peds.female?.[0]);
await run('get_object_models', { search: 'cone', limit: 5 });
await run('search_models', { query: 'ambulance' });
await run('get_model_info', { model: 1238 });
await run('create_workspace', { name: 'smoke', center: P, radius: 30 });
const v = await run('spawn_entity', { workspace: 'smoke', type: 'vehicle', model: 596, placement: { mode: 'road', position: P, lanePosition: 'curb' } });
await run('spawn_entity', { workspace: 'smoke', type: 'object', model: 1238, placement: { mode: 'near', target: v.entity?.id, side: 'back', gap: 1.5 } });
const ped = await run('spawn_entity', { workspace: 'smoke', type: 'ped', model: 280, placement: { mode: 'near', target: v.entity?.id, side: 'left', gap: 0.8, facing: 'towards' }, properties: { pose: 'look' } });
await run('orient_entity', { id: v.entity?.id, mode: 'align_to_road' });
await run('set_entity_transform', { id: ped.entity?.id, move: { forward: 1 }, snapToGround: true });
await run('modify_entity', { id: v.entity?.id, properties: { sirens: true, lightsOn: true, damage: 'light' } });
await run('inspect_entity', { id: v.entity?.id });
await run('get_spatial_relation', { from: v.entity?.id, to: ped.entity?.id });
await run('compute_placement', { type: 'vehicle', model: 416, placement: { mode: 'node', node: 1442188, along: -12, lateral: 3 } });
const val = await run('validate_workspace', { workspace: 'smoke' });
console.log('     valid', val.valid, (val.errors || []).map((e) => e.type), (val.warnings || []).map((w) => w.type));
await run('set_debug_overlay', { workspace: 'smoke', roadArea: { center: P, radius: 60 }, pathNodes: path.nodes });
await run('capture_view', { workspace: 'smoke', overlay: true, daylight: true, width: 800, height: 450 });
await run('set_debug_overlay', { enabled: false, clear: true });
const ex = await run('export_workspace', { workspace: 'smoke', format: 'map' });
console.log('     map lines', ex.text?.split('\n').length);
const gen = await run('export_workspace', { workspace: 'smoke', format: 'generic' });
await run('import_workspace', { data: gen.data, workspace: 'smoke_copy', offset: { x: 0, y: 30 }, keepIds: false });
await run('list_workspaces');
await run('clear_workspace', { all: true });
await run('medical_get_catalog');
await run('medical_build_from_template', { template: 'cardiac_arrest_sidewalk', name: 'smoke_med', near: P });
await run('medical_simulate_patient', { id: 'smoke_med_ped_001' });
await run('medical_simulate_patient', { id: 'smoke_med_ped_001', enable: false });
await run('medical_export_scene', { scene: 'smoke_med' });
await run('medical_live_scene', { action: 'files' });
await run('clear_workspace', { all: true });
await run('get_player_state');
await run('set_camera', { mode: 'get' });
await run('execute_lua', { code: 'getPlayerCount()' });
await run('execute_lua', { side: 'client', code: 'getElementModel(localPlayer)' });
await run('call_export', { resource: 'veh_manager', fn: 'getModelName', args: [416] });
await run('manage_resources', { action: 'info', name: 'medsys' });
await run('get_debug_log', { level: 'error', limit: 5 });
await run('get_health');
await ctx.bridge.close();
setTimeout(() => process.exit(0), 50);
